server:
  port: 1022

# 数据源
spring:
  datasource:
    url: jdbc:mysql://61.162.60.54:3306/huangshuao
    username: root
    password: bitware2022dev
  mvc:
    static-path-pattern: /static/**

  devtools:
    restart:
      # 设置热部署生效
      enabled: true
      # 设置重启的目录
      additional-paths: src/main
      # WEB-INF目录下内容发生更改不重启
      exclude: WEB-INF/*

file:
  upload:
    dir: /src/main/resources/static/images/



# mybatis配置
mybatis:
  mapper-locations: classpath:mapper/userBean/*.xml    # mapper映射文件位置
