server:
  port: 1022

# 数据源
spring:
  datasource:
    url: jdbc:mysql://61.162.60.54:3306/huangshuao
    username: root
    password: bitware2022dev
  mvc:
    static-path-pattern: /static/**

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB


# mybatis配置
mybatis:
  mapper-locations: classpath:mapper/userBean/*.xml    # mapper映射文件位置
